### ISSUE TITLE
Flash of unstyled content

### ISSUE THREAD

**Issue by absowoot** [BartOtten/phoenix_live_favicon#5]
Firstly, I apologize if this is mentioned somewhere and I missed it. I'm really enjoying the library otherwise!

After implementation, updating the favicon causes a flash of unstyled content. It appears that the <head> is completely rewritten when the favicon is updated, so app.css is removed and then added again.

Even if I remove set_dynamic from my handlers, the issue still happens. The only way to fix the issue is to remove ```alias Phx.Live.Favicon``` from my liveview template.

The same issue happens on the [example app](https://github.com/BartOtten/phoenix_live_favicon_example).

Here's a short video: https://www.youtube.com/watch?v=sEuNaJB_3yc

**Comment by BartOtten** [comment]
I did not experience this issue myself so it is an interesting case I have to look into. Thanks for the video; helps a lot.

Which browser + version and OS are you using?

**Comment by absowoot** [comment]
This happens on my Macbook Pro M1 in both Safari and Chrome but interestingly does not happen in Firefox. [Here's another video](https://youtu.be/Ms832cmYK-M).

It seems intermittent in Safari but happens every time in Chrome.

**Comment by BartOtten** [comment]
I have looked into this issue and it seems non-existing at production environment. In development phoenix.css is dynamically loaded which takes just a fraction too long to have a seamless experience. If this is true, it would narrow down the problem space.

Could you verify no flickering occurs when running your app with compiled assets / prod mode?

```
MIX_ENV=prod mix assets.deploy
MIX_ENV=prod SECRET_KEY_BASE="123dsfkjhalei4e56y08t7cghnodstry3fhnwc08oiyceknmrca;t7afywv4nbchviumi756fymop4hgcu1" PHX_HOST="localhost" mix phx.server
```

ps. please also check your browser console as the Example App demonstrated that causing JS errors also causes flickering. 
https://github.com/BartOtten/phoenix_live_favicon_example/commit/4df5491f6d54eb922d347f50380c14a693df53dc

**Comment by dfalling** [comment]
I've hit this issue as well. I've had it for a while but only tracked it down to this today. I can reproduce it on the example app as well, though it's very subtle there (likely because much less CSS to parse than my app.)

- M1 MacBook: Firefox, Chrome, Arc
- Windows 11: Firefox, Chrome

**Comment by BartOtten** [comment]
Hi @dfalling, does it also happen with compiled assets? See: https://github.com/BartOtten/phoenix_live_favicon/issues/5#issuecomment-1446384666

**Comment by dfalling** [comment]
Ah yeah, using compiled assets fixes it locally for me.

I've seen this issue in my production server as well, but it's not reliably reproducible there for me to confirm if the favicon is the issue.

**Comment by natempv** [comment]
I'm encountering this as well. Updating the favicon causes FOUC. Safari and Arc.

**Comment by BartOtten** [comment]
So....this one is really annoying to debug as the behavior is far from consistent. However, it seems that non-Firefox browsers have an issue when the head node is replaced with a clone of itself to trigger a redraw. This forced redraw was in place as changes not alway propagate(d) in the browser

I have created a branch for phoenix_live_head without the force refresh, which seems to solve the issue. Please give it a try and let me know if this fixes the issue and check that changes are still applied. 

To be certain you are running the right Javascript code, please inspect `assets/app.js` in the browser. It should not include `const clone = element.cloneNode(true);`

PR: [PR 10](https://github.com/BartOtten/phoenix_live_head/pull/10)
Branch: [bo/fix-flicker](https://github.com/BartOtten/phoenix_live_head/tree/bo/fix-flicker)

**Comment by dfalling** [comment]
That branch fixed it for me- so much smoother!



For others wanting to test, I just added this to my mix.exs deps:
```
{:phoenix_live_head, git: "git@github.com:BartOtten/phoenix_live_head.git", ref: "ac7d5c6", override: true},
```

I had to build the assets too
```
cd deps/phoenix_live_head
mix deps.get
mix assets.build
```

**Comment by BartOtten** [comment]
@dfalling Thanks for testing. You have earned yourself a honorable mention in the changelog for help with this issue and (especially) the other one.

**Comment by dfalling** [comment]
Happy to help!
